In [8]:
import pandas as pd

ratings = pd.read_csv('ratings.csv')

def classification(data):
  if data['rating'] <= 2 :
    return 'низкий рейтинг'
  elif data['rating'] <= 4 :
    return 'средний рейтинг'
  else:
    return 'высокий рейтинг'

ratings['class'] = ratings.apply(classification, axis=1)
ratings.head(20)

    userId  movieId  rating   timestamp            class
0        1       31     2.5  1260759144  средний рейтинг
1        1     1029     3.0  1260759179  средний рейтинг
2        1     1061     3.0  1260759182  средний рейтинг
3        1     1129     2.0  1260759185   низкий рейтинг
4        1     1172     4.0  1260759205  средний рейтинг
5        1     1263     2.0  1260759151   низкий рейтинг
6        1     1287     2.0  1260759187   низкий рейтинг
7        1     1293     2.0  1260759148   низкий рейтинг
8        1     1339     3.5  1260759125  средний рейтинг
9        1     1343     2.0  1260759131   низкий рейтинг
10       1     1371     2.5  1260759135  средний рейтинг
11       1     1405     1.0  1260759203   низкий рейтинг
12       1     1953     4.0  1260759191  средний рейтинг
13       1     2105     4.0  1260759139  средний рейтинг
14       1     2150     3.0  1260759194  средний рейтинг
15       1     2193     2.0  1260759198   низкий рейтинг
16       1     2294     2.0  1260759108   низкий рейтинг
17       1     2455     2.5  1260759113  средний рейтинг
18       1     2968     1.0  1260759200   низкий рейтинг
19       1     3671     3.0  1260759117  средний рейтинг

In [11]:
geo_data = {
'Центр': ['москва', 'тула', 'ярославль'],
'Северо-Запад': ['петербург', 'псков', 'мурманск'],
'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']
}

keywords = pd.read_csv('keywords.csv')

keywords.head(10)

def key_geo(row):
  for region, cities in geo_data.items():
    for city in cities:
      if  row['keyword'].find(city[:-1]) != -1:
        return region

  return 'undefined'

keywords['region'] = keywords.apply(key_geo, axis=1)

keywords.value_counts('region')

region
undefined         98783
Центр               858
Северо-Запад        265
Дальний Восток       94
dtype: int64

In [14]:
years = list(range(1950, 2011))

def production_year(row):
  for year in years:
    if row['title'].find(str(year)) != -1:
      return year

  return '1900'

movies = pd.read_csv('movies.csv')

movies['year'] = movies.apply(production_year, axis=1)

movies.merge(ratings).groupby('year').mean()['rating'].sort_values(ascending=False).head(10)

year
1957    4.014241
1972    4.011136
1952    4.000000
1954    3.994220
1951    3.983539
1974    3.978704
1962    3.952446
1950    3.915254
1977    3.905786
1964    3.841492
Name: rating, dtype: float64